name: Deployment pipeline

on:
  push:
    branches:
      - main

jobs:
  deployment_pipeline:
    runs-on: ubuntu-20.04
    env:
      SKIP_PREFLIGHT_CHECK: true
      MONGO_URI: ${{ secrets.MONGODB_URI }}
      TEST_MONGO_URI: ${{ secrets.TEST_MONGODB_URI }}
      PORT: 3001
      SECRET: ${{ secrets.JWT_SECRET }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Check style
        run: npm run lint:check

      - name: Build front-end
        run: npm run build

      - name: Run tests
        run: npm run test:ci

      - name: e2e tests
        uses: cypress-io/github-action@v5
        with:
          command: npm run test:e2e
          start: npm run start:test
          wait-on: http://localhost:3001
